Inovacao/Jenkins/routes/Isolar_ENABLE.py
from Balanceadores_ENABLE_NOR.Balanceador_2006_ENABLE import executar_processo_2006_ENABLE
from Balanceadores_ENABLE_NOR.Balanceador_2007_ENABLE import executar_processo_2007_ENABLE
from Balanceadores_ENABLE_NOR.Balanceador_4006_ENABLE import executar_processo_4006_ENABLE
from Balanceadores_ENABLE_NOR.Balanceador_4007_ENABLE import executar_processo_4007_ENABLE
from Balanceadores_ENABLE_NOR.Balanceador_CSS_ENABLE import executar_processo_CSS_ENABLE
from Balanceadores_ENABLE_NOR.Balanceador_CYOI_ENABLE import executar_processo_CYOI_ENABLE
from flask import Blueprint, render_template, request
import logging
from Balanceadores_Isolar_NOR.Balanceador_2006 import executar_processo_2006
from Balanceadores_Isolar_NOR.Balanceador_2007 import executar_processo_2007
from Balanceadores_Isolar_NOR.Balanceador_4006 import executar_processo_4006
from Balanceadores_Isolar_NOR.Balanceador_4007 import executar_processo_4007
from Balanceadores_Isolar_NOR.Balanceador_CSS import executar_processo_CSS
from Balanceadores_Isolar_NOR.Balanceador_CYOI import executar_processo_CYOI
import concurrent.futures
import logging

from dotenv import load_dotenv
import os

# Carrega as variáveis do arquivo .env
load_dotenv()

Variavel_Ambiente_DRIVER = os.getenv('Variavel_Ambiente_DRIVER')

caminho_do_driver = Variavel_Ambiente_DRIVER 


# Criação do Blueprint
Habilitar = Blueprint('Habilitar', __name__)

# Configuração básica do logging
class DevToolsFilter(logging.Filter):
    def filter(self, record):
        return 'DevTools listening on' not in record.getMessage() and \
               'Invalid first_paint' not in record.getMessage()

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# Manipulador de console
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
console_handler.addFilter(DevToolsFilter())

# Manipulador de arquivo
file_handler = logging.FileHandler('app.log')
file_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
file_handler.addFilter(DevToolsFilter())

logger.addHandler(console_handler)
logger.addHandler(file_handler)




@Habilitar.route('/habilitar')
def index4():
    return render_template('index7.html')

@Habilitar.route('/submitHabilitar', methods=['POST'])
def submitIsolar():
    numeros = request.form.get('Numero')
    login = request.form.get('Name')
    senha = request.form.get('PassWord')

    result_message = ""

    if numeros:
        numeros_lista = [numero.strip() for numero in numeros.split(',')]
        processos = [
            ("CSS", executar_processo_CSS_ENABLE),
            ("CYOI", executar_processo_CYOI_ENABLE),
            ("4007", executar_processo_4007_ENABLE),
            ("4006", executar_processo_4006_ENABLE),
            ("2007", executar_processo_2007_ENABLE),
            ("2006", executar_processo_2006_ENABLE)
        ]

        for nome_processo, processo in processos:
            logger.info(f"Iniciando processos para {nome_processo}")
            with concurrent.futures.ThreadPoolExecutor() as executor:
                futures = {executor.submit(processo, caminho_do_driver, login, senha, numero): numero for numero in numeros_lista}
                
                for future in concurrent.futures.as_completed(futures):
                    numero = futures[future]
                    try:
                        message = future.result()
                        result_message += f"{message}<br>"
                        logger.info(message)
                    except Exception as e:
                        result_message += f"Erro ao processar {nome_processo} para o número {numero}: {e}<br>"
                        logger.error(f"Erro ao processar {nome_processo} para o número {numero}: {e}")

        result_message += "Processo concluído com sucesso!<br>"
    else:
        result_message = "Número da máquina não informado.<br>"

    return result_message

Inovacao/Jenkins/routes/Isolar_Nor.py
from flask import Blueprint, render_template, request
import logging
from Balanceadores_Isolar_NOR.Balanceador_2006 import executar_processo_2006
from Balanceadores_Isolar_NOR.Balanceador_2007 import executar_processo_2007
from Balanceadores_Isolar_NOR.Balanceador_4006 import executar_processo_4006
from Balanceadores_Isolar_NOR.Balanceador_4007 import executar_processo_4007
from Balanceadores_Isolar_NOR.Balanceador_CSS import executar_processo_CSS
from Balanceadores_Isolar_NOR.Balanceador_CYOI import executar_processo_CYOI
import concurrent.futures
import logging



# Criação do Blueprint
Isolar_Nor = Blueprint('Isolar_Nor', __name__)

# Configuração básica do logging
class DevToolsFilter(logging.Filter):
    def filter(self, record):
        return 'DevTools listening on' not in record.getMessage() and \
               'Invalid first_paint' not in record.getMessage()

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# Manipulador de console
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
console_handler.addFilter(DevToolsFilter())

# Manipulador de arquivo
file_handler = logging.FileHandler('app.log')
file_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
file_handler.addFilter(DevToolsFilter())

logger.addHandler(console_handler)
logger.addHandler(file_handler)

from dotenv import load_dotenv
import os

# Carrega as variáveis do arquivo .env
load_dotenv()

Variavel_Ambiente_DRIVER = os.getenv('Variavel_Ambiente_DRIVER')

caminho_do_driver = Variavel_Ambiente_DRIVER


@Isolar_Nor.route('/Isolar')
def index4():
    return render_template('index4.html')

@Isolar_Nor.route('/submitIsolar', methods=['POST'])
def submitIsolar():
    numeros = request.form.get('Numero')
    login = request.form.get('Name')
    senha = request.form.get('PassWord')

    result_message = ""

    if numeros:
        numeros_lista = [numero.strip() for numero in numeros.split(',')]
        processos = [
            ("CSS", executar_processo_CSS),
            ("CYOI", executar_processo_CYOI),
            ("4007", executar_processo_4007),
            ("4006", executar_processo_4006),
            ("2007", executar_processo_2007),
            ("2006", executar_processo_2006)
        ]

        for nome_processo, processo in processos:
            logger.info(f"Iniciando processos para {nome_processo}")
            with concurrent.futures.ThreadPoolExecutor() as executor:
                futures = {executor.submit(processo, caminho_do_driver, login, senha, numero): numero for numero in numeros_lista}
                
                for future in concurrent.futures.as_completed(futures):
                    numero = futures[future]
                    try:
                        message = future.result()
                        result_message += f"{message}<br>"
                        logger.info(message)
                    except Exception as e:
                        result_message += f"Erro ao processar {nome_processo} para o número {numero}: {e}<br>"
                        logger.error(f"Erro ao processar {nome_processo} para o número {numero}: {e}")

        result_message += "Processo concluído com sucesso!<br>"
    else:
        result_message = "Número da máquina não informado.<br>"

    return result_message

Inovacao/Jenkins/routes/SSH_Disco_opt.py
import paramiko
import time
from flask import Blueprint, render_template, request
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed

# Configuração de logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# Manipulador de console
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
logger.addHandler(console_handler)

# Manipulador de arquivo
file_handler = logging.FileHandler('app.log')
file_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
logger.addHandler(file_handler)

# Criação do Blueprint para reiniciar
ssh_bp = Blueprint('ssh_bp', __name__)

@ssh_bp.route('/ssh_disco_opt', methods=['GET'])
def ssh_disco_opt():
    return render_template('index8.html')  # Renderiza a página desejada

def execute_ssh_commands(host, username, password):
    port = 22  # Definido como 22 para SSH
    sudo_password = password  # Reutiliza a senha para comandos sudo
    result_message = ""

    # Cria uma sessão SSH
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    try:
        # Conecta ao servidor
        logger.info(f"Conectando ao servidor {host} com o usuário {username}")
        ssh.connect(host, port, username, password)
        result_message += f"Conectado ao servidor {host}<br>"

        # Executa o comando para verificar o tamanho da pasta temp ANTES da exclusão
        size_command_before = 'du -sh /opt/IBM/WAS/WebSphere/AppServer/temp'
        stdin, stdout, stderr = ssh.exec_command(size_command_before)
        size_before = stdout.read().decode().strip()
        result_message += f"Tamanho da pasta temp ANTES da exclusão: {size_before}<br>"
        logger.info(f"Tamanho da pasta temp ANTES da exclusão: {size_before}")

        # Executa o comando que deleta os arquivos temporários como sudo
        delete_command = 'sudo find /opt/IBM/WAS/WebSphere/AppServer/temp -name "*.tmp" -delete'
        stdin, stdout, stderr = ssh.exec_command(delete_command)
        stdin.write(sudo_password + '\n')
        stdin.flush()
        time.sleep(2)  # Aguardando o comando ser executado

        # Verifica o resultado do comando
        output = stdout.read().decode().strip()
        result_message += f"Resultado da exclusão de arquivos temporários:<br>{output}<br>"
        logger.info(f"Resultado da exclusão: {output}")

        error_output = stderr.read().decode()
        if error_output:
            result_message += f"Erro: {error_output}<br>"
            logger.error(f"Erro ao excluir arquivos: {error_output}")

        # Executa o comando para verificar o tamanho da pasta temp DEPOIS da exclusão
        size_command_after = 'du -sh /opt/IBM/WAS/WebSphere/AppServer/temp'
        stdin, stdout, stderr = ssh.exec_command(size_command_after)
        size_after = stdout.read().decode().strip()
        result_message += f"Tamanho da pasta temp DEPOIS da exclusão: {size_after}<br>"
        logger.info(f"Tamanho da pasta temp DEPOIS da exclusão: {size_after}")

    except Exception as e:
        result_message += f"Erro ao conectar ou executar o comando no servidor {host}: {str(e)}<br>"
        logger.error(f"Erro ao conectar ou executar o comando: {str(e)}")

    finally:
        ssh.close()
        logger.info(f"Conexão SSH encerrada para o servidor {host}.")

    return result_message

# Rota para processar a solicitação (POST)
@ssh_bp.route('/ssh_disco_opt', methods=['POST'])
def ssh_clean():
    # Recebe os dados do formulário
    hosts_string = request.form.get('Numero')  # Pega a string de hosts
    username = request.form.get('Name')
    password = request.form.get('PassWord')

    # Separa os hosts por vírgula e remove espaços em branco
    hosts = [host.strip() for host in hosts_string.split(',')] if hosts_string else []
    logger.info(f"Hosts recebidos para conexão: {hosts}")

    result_messages = []
    
    if not hosts or not username or not password:
        result_message = "Parâmetros inválidos!"
        logger.error(result_message)
        return result_message

    # Usando ThreadPoolExecutor para executar comandos em paralelo
    with ThreadPoolExecutor() as executor:
        future_to_host = {executor.submit(execute_ssh_commands, host, username, password): host for host in hosts}
        
        for future in as_completed(future_to_host):
            host = future_to_host[future]
            try:
                result = future.result()
                result_messages.append(result)
            except Exception as e:
                logger.error(f"Erro ao processar o servidor {host}: {str(e)}")
                result_messages.append(f"Erro ao processar o servidor {host}: {str(e)}")

    # Retorna os resultados concatenados
    return "<br>".join(result_messages)

Inovacao/Jenkins/routes/SSH_Outofmemory.py
import paramiko
import time
from flask import Blueprint, render_template, request
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed

# Configuração de logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# Manipulador de console
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
logger.addHandler(console_handler)

# Manipulador de arquivo
file_handler = logging.FileHandler('app.log')
file_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
logger.addHandler(file_handler)

# Criação do Blueprint para mover arquivos
move_bp = Blueprint('move_bp', __name__)

@move_bp.route('/move_files', methods=['GET'])
def move_files():
    return render_template('index_move.html')  # Renderiza a página desejada

def move_files_ssh(host, username, password):
    port = 22
    sudo_password = password
    result_message = ""

    # Cria a sessão SSH
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    try:
        # Conecta ao servidor
        logger.info(f"Conectando ao servidor {host} com o usuário {username}")
        ssh.connect(host, port, username, password)
        result_message += f"Conectado ao servidor {host}<br>"

        # Comando para listar o conteúdo da pasta antes da movimentação
        list_before_command = 'ls -lh /opt/IBM/WAS/WebSphere/AppServer/profiles/sicoob/'
        stdin, stdout, stderr = ssh.exec_command(list_before_command)
        files_before = stdout.read().decode()
        result_message += f"Arquivos ANTES da movimentação:<br>{files_before}<br>"
        logger.info(f"Arquivos ANTES da movimentação: {files_before}")

        # Comando para mover os arquivos
        move_command = 'cd /opt/IBM/WAS/WebSphere/AppServer/profiles/sicoob/ && sudo mv *.dmp *.txt *.phd *.trc /media/dump/'
        stdin, stdout, stderr = ssh.exec_command(move_command)
        stdin.write(sudo_password + '\n')
        stdin.flush()
        time.sleep(2)  # Aguardar o tempo necessário para o comando ser executado

        # Exibe a saída do comando de mover arquivos
        output = stdout.read().decode()
        result_message += f"Resultado do comando sudo (mover arquivos):<br>{output}<br>"
        logger.info(f"Resultado do comando sudo (mover arquivos): {output}")

        # Exibe qualquer erro retornado
        error_output = stderr.read().decode()
        if error_output:
            result_message += f"Erro: {error_output}<br>"
            logger.error(f"Erro ao mover arquivos: {error_output}")

        # Comando para listar o conteúdo da pasta depois da movimentação
        list_after_command = 'ls -lh /opt/IBM/WAS/WebSphere/AppServer/profiles/sicoob/'
        stdin, stdout, stderr = ssh.exec_command(list_after_command)
        files_after = stdout.read().decode()
        result_message += f"Arquivos DEPOIS da movimentação:<br>{files_after}<br>"
        logger.info(f"Arquivos DEPOIS da movimentação: {files_after}")

    except Exception as e:
        result_message += f"Erro ao conectar ou executar o comando no servidor {host}: {str(e)}<br>"
        logger.error(f"Erro ao conectar ou executar o comando: {str(e)}")

    finally:
        ssh.close()
        logger.info(f"Conexão SSH encerrada para o servidor {host}.")

    return result_message

# Rota para processar a solicitação (POST)
@move_bp.route('/move_files', methods=['POST'])
def move_files_action():
    # Recebe os dados do formulário
    hosts = request.form.getlist('Numero')  # Supondo que você envie uma lista de números
    username = request.form.get('Name')
    password = request.form.get('PassWord')

    result_messages = []
    
    if not hosts or not username or not password:
        result_message = "Parâmetros inválidos!"
        logger.error(result_message)
        return result_message

    # Usando ThreadPoolExecutor para executar comandos em paralelo
    with ThreadPoolExecutor() as executor:
        future_to_host = {executor.submit(move_files_ssh, host, username, password): host for host in hosts}
        
        for future in as_completed(future_to_host):
            host = future_to_host[future]
            try:
                result = future.result()
                result_messages.append(result)
            except Exception as e:
                logger.error(f"Erro ao processar o servidor {host}: {str(e)}")
                result_messages.append(f"Erro ao processar o servidor {host}: {str(e)}")

    # Retorna os resultados concatenados
    return "<br>".join(result_messages)

Inovacao/Jenkins/templates/index4.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema de Reinício</title>
    <style>
        :root {
            --primary-bg-color: #1f1f1f;
            --secondary-bg-color: #2c2c2c;
            --primary-text-color: #ffffff;
            --secondary-text-color: #b0b0b0;
            --input-bg-color: #3c3c3c;
            --input-border-color: #555;
            --input-focus-border-color: #008cba;
            --button-bg-color: #008cba;
            --button-hover-bg-color: #007299;
            --button-text-color: #ffffff;
            --border-radius: 6px;
            --box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
            --sidebar-width: 250px;
            --progress-bar-width: 100%;
            --navbar-height: 80px;
            --form-width: 600px;
        }

        body {
            margin: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: var(--primary-bg-color);
            overflow: hidden;
        }

        .navbar {
            background-color: var(--secondary-bg-color);
            height: var(--navbar-height);
            width: 100%;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
            position: fixed;
            top: 0;
            left: 0;
            z-index: 1000;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 0 1rem;
        }

        .navbar img {
            height: 60px;
            max-width: 100%;
        }

        .sidebar {
            width: var(--sidebar-width);
            background-color: var(--secondary-bg-color);
            color: var(--primary-text-color);
            display: flex;
            flex-direction: column;
            padding: 1rem;
            box-shadow: 2px 0 5px rgba(0, 0, 0, 0.3);
            position: fixed;
            height: calc(100vh - var(--navbar-height));
            top: var(--navbar-height);
            left: 0;
            z-index: 1000;
            overflow-y: auto;
        }

        .sidebar a {
            color: var(--primary-text-color);
            padding: 10px 15px;
            text-decoration: none;
            border-radius: var(--border-radius);
            display: block;
            margin-bottom: 10px;
            transition: background-color 0.3s;
        }

        .sidebar a:hover {
            background-color: var(--button-hover-bg-color);
        }

        .sidebar a.selected {
            background-color: #4CAF50;
            font-weight: bold;
        }

        .main-content {
            margin-left: var(--sidebar-width);
            margin-top: var(--navbar-height);
            padding: 1rem;
            width: calc(100% - var(--sidebar-width));
            height: calc(100vh - var(--navbar-height));
            overflow-y: auto;
            box-sizing: border-box;
        }

        .container {
            background-color: var(--secondary-bg-color);
            padding: 2rem;
            border-radius: var(--border-radius);
            box-shadow: var(--box-shadow);
            width: var(--form-width);
            margin: 2rem auto;
            box-sizing: border-box;
        }

        h2 {
            font-size: 1.2rem;
            color: var(--primary-text-color);
            margin-bottom: 1.5rem;
            text-align: center;
        }

        form {
            display: flex;
            flex-direction: column;
            gap: 1.2rem;
        }

        .form-group {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
        }

        label {
            font-size: 1rem;
            color: var(--secondary-text-color);
        }

        input[type="text"],
        input[type="password"] {
            padding: 0.75rem;
            background-color: var(--input-bg-color);
            border: 1px solid var(--input-border-color);
            border-radius: var(--border-radius);
            color: var(--primary-text-color);
            outline: none;
            transition: border-color 0.3s ease;
        }

        input[type="text"]:focus,
        input[type="password"]:focus {
            border-color: var(--input-focus-border-color);
        }

        button {
            padding: 0.75rem;
            background-color: var(--button-bg-color);
            border: none;
            border-radius: var(--border-radius);
            color: var(--button-text-color);
            font-size: 1.1rem;
            cursor: pointer;
            transition: background-color 0.3s ease;
            box-shadow: var(--box-shadow);
        }

        button:hover {
            background-color: var(--button-hover-bg-color);
        }

        button:active {
            transform: translateY(2px);
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        }

        #progressContainer {
            display: none; /* Começa invisível */
            width: var(--progress-bar-width);
            margin: 1rem auto;
            text-align: center;
        }

        #progressBar {
            width: 0%;
            height: 8px;
            background-color: #4caf50;
            border-radius: var(--border-radius);
            transition: width 0.3s ease;
        }

        #resultMessageContainer {
            background-color: var(--secondary-bg-color);
            color: var(--primary-text-color);
            padding: 10px;
            border-radius: var(--border-radius);
            box-shadow: var(--box-shadow);
            margin-top: 20px;
            max-height: 300px;
            overflow: auto;
            display: none;
        }

        #resultMessage {
            opacity: 0;
            transition: opacity 0.5s ease, transform 0.5s ease;
            transform: translateY(-20px);
        }

        #resultMessage.show {
            opacity: 1;
            transform: translateY(0);
        }

        #processingMessage {
            display: none;
            color: var(--primary-text-color);
            margin-bottom: 1rem;
            text-align: center;
        }

        @media (max-width: 768px) {
            .sidebar {
                width: 200px;
            }

            .main-content {
                margin-left: 200px;
            }

            .navbar img {
                height: 50px;
            }

            .container {
                padding: 1rem;
                margin: 1rem auto;
                width: calc(100% - 2rem);
            }

            h2 {
                font-size: 1.25rem;
            }
        }

        @media (max-width: 480px) {
            .sidebar {
                width: 150px;
            }

            .main-content {
                margin-left: 150px;
            }

            .navbar img {
                height: 40px;
            }

            .container {
                padding: 0.5rem;
                margin: 0.5rem auto;
                width: calc(100% - 1rem);
            }

            h2 {
                font-size: 1rem;
            }
        }
    </style>
      <style>
        .dropdown {
            position: relative;
            display: inline-block;
        }
    
        .dropbtn {
            background-color: var(--secondary-bg-color);
            color: var(--primary-text-color);
            padding: 10px 15px;
            border: none;
            text-align: left;
            cursor: pointer;
            width: 100%;
        }
    
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: var(--secondary-bg-color);
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }
    
        .dropdown-content a {
            color: var(--primary-text-color);
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }
    
        .dropdown-content a:hover {
            background-color: #008cba;
        }
    
        .dropdown:hover .dropdown-content {
            display: block;
        }
    
        .dropdown:hover .dropbtn {
            background-color: #4CAF50;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <img src="{{ url_for('static', filename='sicoob-novo-logo-612F40FA2F-seeklogo.com.png') }}" alt="Logo do Sistema">
    </div>

    <div class="sidebar">
        <div class="dropdown">
            <button class="dropbtn" class="selected">RELATÓRIOS DE RESTART BUILDS</button>
            <div class="dropdown-content">
                <a href="/pesquisa" >Restart Builds Whebsphere</a>
                <a href="/pesquisa2">Restart Builds Liberty</a>
                <a href="/pesquisa3">Restart Builds STRB</a>
            </div>
        </div>
        <a href="/">RESTART CTRP, TRNP E WASP</a>
        <!-- <a href="/restart">RESTART CLUSTER</a>
        <a href="/restart2">RESTART SERVIÇO</a> -->
        <a href="/Isolar" class="selected">BALANCEADOR ISOLAR-NO (MODO:PARALELO)</a>
        <a href="/habilitar">BALANCEADOR HABILITAR (MODO:PARALELO)</a>
        <a href="/IsolarERestartEnable">AÇÃO DE 1° NIVEL (MODO:PARALELO)</a>
        <a href="/IsolarERestartEnable_SEGUENCIAL">AÇÃO DE 1° NIVEL (MODO:SEQUENCIAL)</a>
        <a href="/Pesquisa_CCS">PESQUISA NO POOL</a>

        <div class="dropdown">
            <button class="dropbtn" >Automação SSH</button>
            <div class="dropdown-content">
                <a href="/ssh_disco_opt" >Disco-opt (limpa a pasta temp)</a>
                <a href="/move_files">Outofmemory (Mover arquivos .trc .txt .dmp .phd para pasta dump)</a>
            </div>
        </div>
    </div>

    <div class="main-content">
        <div class="container">
            <h2>Processo de isolar maquina no node (MODO:PARALELO)</h2>
            
            <form id="restartForm">
                <div class="form-group">
                    <label for="Name">Login Balanceador:</label>
                    <input type="text" id="Name" name="Name" required>
                </div>
                <div class="form-group">
                    <label for="PassWord">Senha Balanceador:</label>
                    <input type="password" id="PassWord" name="PassWord" required>
                </div>
                <div class="form-group">
                    <label for="Numero">Número da Máquina:</label>
                    <input type="text" id="Numero" name="Numero" required>
                </div>
                <button type="submit">ISOLAR</button>
                <!-- Barra de progresso centralizada abaixo do botão -->
                <div id="progressContainer">
                    <div id="progressBar"></div>
                </div>
            </form>
            <div id="processingMessage">Processando...</div>
            <div id="resultMessageContainer">
                <div id="resultMessage"></div>
            </div>
        </div>
    </div>

    <script>
        document.getElementById('restartForm').addEventListener('submit', function(event) {
            event.preventDefault();

            var formData = new FormData(this);
            var processingMessage = document.getElementById('processingMessage');
            var resultMessageContainer = document.getElementById('resultMessageContainer');
            var resultMessage = document.getElementById('resultMessage');
            var progressContainer = document.getElementById('progressContainer');
            var progressBar = document.getElementById('progressBar');

            // Exibe a mensagem de processamento e a barra de progresso
            processingMessage.style.display = 'block';
            progressContainer.style.display = 'block'; // Garante que o contêiner esteja visível
            progressBar.style.width = '0%';

            // Simula o progresso da barra
            var width = 0;
            var interval = setInterval(function() {
                if (width >= 100) {
                    clearInterval(interval);
                } else {
                    width++;
                    progressBar.style.width = width + '%';
                }
            }, 50); // Intervalo ajustado para uma animação suave

            fetch("{{ url_for('Isolar_Nor.submitIsolar') }}", {
                method: 'POST',
                body: formData
            })
            .then(response => response.text())
            .then(data => {
                clearInterval(interval);
                processingMessage.style.display = 'none';
                progressContainer.style.display = 'none'; // Esconde o contêiner ao final
                resultMessage.innerHTML = data;
                
                // Exibe a mensagem de resultado com efeito de deslizamento
                resultMessageContainer.style.display = 'block';
                resultMessage.classList.add('show');
            })
            .catch(error => {
                clearInterval(interval);
                processingMessage.style.display = 'none';
                progressContainer.style.display = 'none'; // Esconde o contêiner ao final
                resultMessage.innerHTML = 'Ocorreu um erro: ' + error;
                
                // Exibe a mensagem de resultado com efeito de deslizamento
                resultMessageContainer.style.display = 'block';
                resultMessage.classList.add('show');
            });
        });
    </script>
</body>
</html>